VIA_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes

BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
OLED_ENABLE = no

EXTRAFLAGS += -Wno-error=unused-const-variable
