name: Build QMK UF2 Firmware (keyball39 RP2040)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install QMK
        run: |
          pip install qmk

      - name: Setup QMK
        run: |
          qmk setup -y

      - name: Build UF2 Firmware
        run: |
          qmk compile -kb keyball/keyball39 -km via

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: keyball39-rp2040-uf2
          path: ./**/.uf2
